vich_uploader:
    db_driver: orm

    mappings:
        barman:
           uri_prefix: /image/barman
           upload_destination: '%kernel.project_dir%/public/image/barman'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
        produit: 
            uri_prefix: /image/produit
            upload_destination: '%kernel.project_dir%/public/image/produit'
        bar: 
            uri_prefix: /image/bar
            upload_destination: '%kernel.project_dir%/public/image/bar'


